language: python

python: "3.8"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

install:
  - .travis/install.sh

before_script:
  - pre-commit run --all-files

script:
  - pytest

after_script:
  - codecov

deploy:
  provider: pypi
  username: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  skip_existing: true
