language: python
python: "3.8"
cache: pip
install:
  - pip install -r dev-requirements.txt
before_script:
  - black --check .
script:
  - flake8 .
deploy:
  provider: pypi
  username: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  skip_existing: true