language: python

python: "3.8"

cache: pip

install:
  - .travis/install.sh

before_script:
  - black --check .

script:
  - flake8 .
  - pytest

after_script:
  - codecov

deploy:
  provider: pypi
  username: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  skip_existing: true