language: python

python:
  - "3.8"
  - "3.9"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

install:
  - pip install -r dev-requirements.txt

before_script:
  - pre-commit run --all-files

script:
  - tox

after_script:
  - codecov

deploy:
  provider: pypi
  username: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  skip_existing: true
